In [2]:
from numpy import *
import numpy as np

In [ ]:
# 알아야 할 함수
#1. Zip
#2. type
#3. isinstance(instance,class)

In [18]:
# numpy 자료형부터 vectorto matrix
v1 = array([1,2,3]);
v2 = array([3,2,1]);

In [68]:
# 제일 많이 쓸 함수 ! 
# dot
print(dot(v1,v2));
print(v1.dot(v2));
print(v1 @ v2);

10
10
10
(3,)
int32
[[1 2]
 [3 4]]
[10  2  3  4]
[1 2 3 4]


In [66]:
# shape
print(v1.shape);
M = array([v1.tolist(),v2.tolist()]);

array([10,  2,  3,  4])

In [69]:
# dtype
print(M.dtype);

int32


In [100]:
# reshape : Copy를 하지 않고, Reference.. 동일한 메모리 주소, view만 다름 ! copy method로 문제해결
print(M.reshape(3,-1));
v3 = array([1,2,3,4]);
reshaped_v3 = v3.reshape(2,2);
print(reshaped_v3);
old_v3 = v3.copy();
reshaped_v3[0,0]=10;
print(v3);
print(old_v3);

[[1 2]
 [3 3]
 [2 1]]
[[1 2]
 [3 4]]
[10  2  3  4]
[1 2 3 4]


array([[1, 2],
       [3, 3],
       [2, 1]])

In [89]:
print(old_v3.base is None);
print(v3.base is None);
print(reshaped_v3.base is None);

True
True
False


In [77]:
# stacking
print(hstack([v1,v2]))
print(vstack([v1,v2]));
print(column_stack([v1,v2]));

[1 2 3 3 2 1]
[[1 2 3]
 [3 2 1]]
[[1 3]
 [2 2]
 [3 1]]


In [83]:
# sum
print(M.sum(axis=0));
print(M.sum(axis=1));

[4 4 4]
[6 6]


In [50]:
# page 74 & 75
print(M[0][1]);
print(M[0,1]);
print(M[0,:]);
print(M[:,0]);

2
2
[1 2 3]
[1 3]


In [56]:
# tanspose도 view임
print(M.shape);
print(M.transpose().shape);
print(M @ M.transpose());

(2, 3)
(3, 2)
[[14 10]
 [10 14]]


In [97]:
# condition
print(v1);
print(array([0.1,0.2,0.3])>=0.2);
print(v1[array([0.1,0.2,0.3])>=0.2]);
#type casting
print(where(v1>=2,v1,False));

[1 2 3]
[False  True  True]
[2 3]
[0 2 3]


In [ ]:
# page 77,97,98쪽은 왠만하면 외우기